# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180924_0315'),
        ('orders', '0005_auto_20180922_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Billing_Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipping_Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='addresses.Address'),
        ),
    ]
