# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180924_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Billing_Address',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Shipping_Address',
            new_name='shipping_address',
        ),
    ]
